export const MONSTER_ATTRIBUTES = [
  { ja: '炎', en: 'Fire' },
  { ja: '電気', en: 'Electric' },
  { ja: '水', en: 'Water' },
  { ja: '草', en: 'Grass' },
  { ja: '氷', en: 'Ice' },
  { ja: '格闘', en: 'Fighting' },
  { ja: '毒', en: 'Poison' },
  { ja: '地面', en: 'Ground' },
  { ja: '飛行', en: 'Flying' },
  { ja: 'エスパー', en: 'Psychic' },
  { ja: '虫', en: 'Bug' },
  { ja: '岩', en: 'Rock' },
  { ja: 'ゴースト', en: 'Ghost' },
  { ja: 'ドラゴン', en: 'Dragon' },
  { ja: '悪', en: 'Dark' },
  { ja: '鋼', en: 'Steel' },
  { ja: 'フェアリー', en: 'Fairy' },
];
